export enum QueryKeys {
  messages = 'messages',
  sharedMessages = 'sharedMessages',
  sharedStartupConfig = 'sharedStartupConfig',
  sharedLinks = 'sharedLinks',
  allConversations = 'allConversations',
  archivedConversations = 'archivedConversations',
  searchConversations = 'searchConversations',
  conversation = 'conversation',
  searchEnabled = 'searchEnabled',
  user = 'user',
  name = 'name', // user key name
  models = 'models',
  balance = 'balance',
  endpoints = 'endpoints',
  tokenConfig = 'tokenConfig',
  presets = 'presets',
  searchResults = 'searchResults',
  tokenCount = 'tokenCount',
  availablePlugins = 'availablePlugins',
  startupConfig = 'startupConfig',
  assistants = 'assistants',
  assistant = 'assistant',
  agents = 'agents',
  agent = 'agent',
  files = 'files',
  fileConfig = 'fileConfig',
  tools = 'tools',
  toolAuth = 'toolAuth',
  toolCalls = 'toolCalls',
  mcpTools = 'mcpTools',
  mcpConnectionStatus = 'mcpConnectionStatus',
  mcpAuthValues = 'mcpAuthValues',
  agentTools = 'agentTools',
  actions = 'actions',
  assistantDocs = 'assistantDocs',
  agentDocs = 'agentDocs',
  fileDownload = 'fileDownload',
  filePreview = 'filePreview',
  voices = 'voices',
  customConfigSpeech = 'customConfigSpeech',
  prompts = 'prompts',
  prompt = 'prompt',
  promptGroups = 'promptGroups',
  allPromptGroups = 'allPromptGroups',
  promptGroup = 'promptGroup',
  projects = 'projects',
  project = 'project',
  projectConversations = 'projectConversations',
  categories = 'categories',
  randomPrompts = 'randomPrompts',
  agentCategories = 'agentCategories',
  marketplaceAgents = 'marketplaceAgents',
  roles = 'roles',
  rolesList = 'rolesList',
  conversationTags = 'conversationTags',
  health = 'health',
  userTerms = 'userTerms',
  banner = 'banner',
  /* Memories */
  memories = 'memories',
  principalSearch = 'principalSearch',
  accessRoles = 'accessRoles',
  resourcePermissions = 'resourcePermissions',
  effectivePermissions = 'effectivePermissions',
  graphToken = 'graphToken',
  /* MCP Servers */
  mcpServers = 'mcpServers',
  mcpServer = 'mcpServer',
  /* Active Jobs */
  activeJobs = 'activeJobs',
  /* Agent API Keys */
  agentApiKeys = 'agentApiKeys',
  /* Skills */
  skills = 'skills',
  skill = 'skill',
  skillFiles = 'skillFiles',
  skillFileContent = 'skillFileContent',
  /* Skill tree (phase 2 — filesystem-style node view) */
  skillTree = 'skillTree',
  skillNodeContent = 'skillNodeContent',
  /* Tool favorites (starred marketplace items) */
  toolFavorites = 'toolFavorites',
  /* Per-user skill active/inactive overrides */
  skillStates = 'skillStates',
  /* General user favorites */
  favorites = 'favorites',
  /* Billing */
  billingPlans = 'billingPlans',
  billingCreditPacks = 'billingCreditPacks',
  billingSubscription = 'billingSubscription',
  billingTransactions = 'billingTransactions',
  /* Image Generation */
  imageGenProviders = 'imageGenProviders',
  imageGenHistory = 'imageGenHistory',
  /* Video Generation */
  videoGenProviders = 'videoGenProviders',
  videoGenHistory = 'videoGenHistory',
  videoGenStatus = 'videoGenStatus',
  /* Knowledge / RAG Workspace */
  knowledgeDocuments = 'knowledgeDocuments',
  knowledgeCollections = 'knowledgeCollections',
  knowledgeCollectionAnalytics = 'knowledgeCollectionAnalytics',
  knowledgeAdminSettings = 'knowledgeAdminSettings',
  knowledgeDocumentDetail = 'knowledgeDocumentDetail',
  knowledgeImportJobs = 'knowledgeImportJobs',
  knowledgeImportJob = 'knowledgeImportJob',
  /* Prompt Marketplace */
  marketplacePrompts = 'marketplacePrompts',
  marketplaceFeatured = 'marketplaceFeatured',
  marketplaceCategories = 'marketplaceCategories',
  marketplaceFavorites = 'marketplaceFavorites',
  /* Admin / Super Admin */
  adminDashboardStats = 'adminDashboardStats',
  adminUserDetail = 'adminUserDetail',
  adminRevenue = 'adminRevenue',
  adminSubscriptions = 'adminSubscriptions',
  adminProviders = 'adminProviders',
  adminModels = 'adminModels',
  adminAnnouncements = 'adminAnnouncements',
  adminHealth = 'adminHealth',
  adminFeatures = 'adminFeatures',
  adminAuditLog = 'adminAuditLog',
  adminAnalytics = 'adminAnalytics',
  adminLockedUsers = 'adminLockedUsers',
notificationsList = 'notificationsList',
notificationsUnreadCount = 'notificationsUnreadCount',
notificationPreferences = 'notificationPreferences',
  integrationsList = 'integrationsList',
  integrationOAuthStatus = 'integrationOAuthStatus',
  orgsList = 'orgsList',
  orgDetail = 'orgDetail',
  orgMembers = 'orgMembers',
  orgInvites = 'orgInvites',
  orgTeams = 'orgTeams',
  orgTeamMembers = 'orgTeamMembers',
  orgBillingSubscription = 'orgBillingSubscription',
  orgBillingBalance = 'orgBillingBalance',
  orgBillingTransactions = 'orgBillingTransactions',
  orgCreditSummary = 'orgCreditSummary',
  sharedFolders = 'sharedFolders',
  teamPrompts = 'teamPrompts',
  teamAgents = 'teamAgents',
  inviteInfo = 'inviteInfo',
  branding = 'branding',
  brandingSSLStatus = 'brandingSSLStatus',
  brandingStatus = 'brandingStatus',
  brandingDocs = 'brandingDocs',
  workflows = 'workflows',
  workflow = 'workflow',
  workflowExecutions = 'workflowExecutions',
  workflowExecution = 'workflowExecution',
  workflowQueueStatus = 'workflowQueueStatus',
  /* Provider Management */
  providerOverview = 'providerOverview',
  providersList = 'providersList',
  providerDetail = 'providerDetail',
  providerKeys = 'providerKeys',
  providerModels = 'providerModels',
  routingRules = 'routingRules',
  providerUsage = 'providerUsage',
  providerCosts = 'providerCosts',
  providerHealthHistory = 'providerHealthHistory',
  systemDefaults = 'systemDefaults',
  /* Media */
  mediaPresets = 'mediaPresets',
  mediaCreditCosts = 'mediaCreditCosts',
  mediaHistory = 'mediaHistory',
  adminMediaModels = 'adminMediaModels',
  adminMediaRoutingRules = 'adminMediaRoutingRules',
  adminMediaAnalytics = 'adminMediaAnalytics',
}

// Dynamic query keys that require parameters
export const DynamicQueryKeys = {
  agentFiles: (agentId: string) => ['agentFiles', agentId] as const,
} as const;

export enum MutationKeys {
  createAgentApiKey = 'createAgentApiKey',
  deleteAgentApiKey = 'deleteAgentApiKey',
  fileUpload = 'fileUpload',
  fileDelete = 'fileDelete',
  updatePreset = 'updatePreset',
  deletePreset = 'deletePreset',
  loginUser = 'loginUser',
  logoutUser = 'logoutUser',
  refreshToken = 'refreshToken',
  avatarUpload = 'avatarUpload',
  speechToText = 'speechToText',
  textToSpeech = 'textToSpeech',
  assistantAvatarUpload = 'assistantAvatarUpload',
  agentAvatarUpload = 'agentAvatarUpload',
  updateAction = 'updateAction',
  updateAgentAction = 'updateAgentAction',
  deleteAction = 'deleteAction',
  deleteAgentAction = 'deleteAgentAction',
  revertAgentVersion = 'revertAgentVersion',
  deleteUser = 'deleteUser',
  updateRole = 'updateRole',
  enableTwoFactor = 'enableTwoFactor',
  verifyTwoFactor = 'verifyTwoFactor',
  updateMemoryPreferences = 'updateMemoryPreferences',
  createProject = 'createProject',
  updateProject = 'updateProject',
  deleteProject = 'deleteProject',
  assignConversationToProject = 'assignConversationToProject',
  /* Skill mutations from the original UI PR — tree/node operations are
   * phase 2 and currently stubbed in the data-service layer. */
  createSkillNode = 'createSkillNode',
  updateSkillNode = 'updateSkillNode',
  deleteSkillNode = 'deleteSkillNode',
  updateSkillNodeContent = 'updateSkillNodeContent',
  convoPin = 'convoPin',
  userProfileUpdate = 'userProfileUpdate',
  /* Billing */
  createBillingCheckout = 'createBillingCheckout',
  createBillingPortal = 'createBillingPortal',
  cancelBillingSubscription = 'cancelBillingSubscription',
  /* Image Generation */
  generateImages = 'generateImages',
  deleteImageGenHistory = 'deleteImageGenHistory',
  toggleImageGenFavorite = 'toggleImageGenFavorite',
  /* Video Generation */
  generateVideo = 'generateVideo',
  deleteVideoGenHistory = 'deleteVideoGenHistory',
  toggleVideoGenFavorite = 'toggleVideoGenFavorite',
  /* Knowledge / RAG Workspace */
  uploadKnowledgeDocument = 'uploadKnowledgeDocument',
  deleteKnowledgeDocument = 'deleteKnowledgeDocument',
  createKnowledgeCollection = 'createKnowledgeCollection',
  updateKnowledgeCollection = 'updateKnowledgeCollection',
  deleteKnowledgeCollection = 'deleteKnowledgeCollection',
  addFileToKnowledgeCollection = 'addFileToKnowledgeCollection',
  removeFileFromKnowledgeCollection = 'removeFileFromKnowledgeCollection',
  knowledgeSearch = 'knowledgeSearch',
  knowledgeChat = 'knowledgeChat',
  quickKnowledgeAction = 'quickKnowledgeAction',
  renameKnowledgeDocument = 'renameKnowledgeDocument',
  reindexKnowledgeDocument = 'reindexKnowledgeDocument',
  moveKnowledgeDocument = 'moveKnowledgeDocument',
  updateKnowledgeAdminSettings = 'updateKnowledgeAdminSettings',
  uploadKnowledgeDocumentAsync = 'uploadKnowledgeDocumentAsync',
  cancelKnowledgeImportJob = 'cancelKnowledgeImportJob',
  retryKnowledgeImportJob = 'retryKnowledgeImportJob',
  reindexKnowledgeCollectionAsync = 'reindexKnowledgeCollectionAsync',
  /* Prompt Marketplace */
  toggleMarketplaceFavorite = 'toggleMarketplaceFavorite',
  /* Admin / Super Admin */
  updateAdminUserRole = 'updateAdminUserRole',
  adjustAdminCredits = 'adjustAdminCredits',
  cancelAdminSubscription = 'cancelAdminSubscription',
  createAdminAnnouncement = 'createAdminAnnouncement',
  updateAdminAnnouncement = 'updateAdminAnnouncement',
  deleteAdminAnnouncement = 'deleteAdminAnnouncement',
  unlockAdminUser = 'unlockAdminUser',
  notificationPreferences = 'notificationPreferences',
  saveIntegrationConfig = 'saveIntegrationConfig',
  deleteIntegration = 'deleteIntegration',
  integrationOAuthRefresh = 'integrationOAuthRefresh',
  integrationOAuthDisconnect = 'integrationOAuthDisconnect',
  workflowCancelExecution = 'workflowCancelExecution',
  workflowRetryExecution = 'workflowRetryExecution',
  updateNotificationPreferences = 'updateNotificationPreferences',
  subscribePushNotification = 'subscribePushNotification',
  unsubscribePushNotification = 'unsubscribePushNotification',
  sendNotificationDigest = 'sendNotificationDigest',
  /* Org Billing */
  allocateOrgCredits = 'allocateOrgCredits',
  initializeOrgBilling = 'initializeOrgBilling',
  /* Shared Content */
  createSharedFolder = 'createSharedFolder',
  updateSharedFolder = 'updateSharedFolder',
  deleteSharedFolder = 'deleteSharedFolder',
  shareTeamPrompt = 'shareTeamPrompt',
  unshareTeamPrompt = 'unshareTeamPrompt',
  shareTeamAgent = 'shareTeamAgent',
  unshareTeamAgent = 'unshareTeamAgent',
  acceptInvite = 'acceptInvite',
  uploadBrandingImage = 'uploadBrandingImage',
  verifyBrandingDomain = 'verifyBrandingDomain',
  costOptimizerSuggest = 'costOptimizerSuggest',
  costOptimizerApply = 'costOptimizerApply',
  costOptimizerSavings = 'costOptimizerSavings',
  costOptimizerRecent = 'costOptimizerRecent',
  costOptimizerModels = 'costOptimizerModels',
  costOptimizerProviders = 'costOptimizerProviders',
  promptOptimizerOptimize = 'promptOptimizerOptimize',
  promptOptimizerModes = 'promptOptimizerModes',
  agentMarketplaceList = 'agentMarketplaceList',
  agentMarketplaceById = 'agentMarketplaceById',
  agentMarketplaceInstalled = 'agentMarketplaceInstalled',
  agentMarketplaceReviews = 'agentMarketplaceReviews',
  agentMarketplaceFollowers = 'agentMarketplaceFollowers',
  agentMarketplaceFollowing = 'agentMarketplaceFollowing',
  agentMarketplaceRevenue = 'agentMarketplaceRevenue',
  agentMarketplaceCreatorProfile = 'agentMarketplaceCreatorProfile',
  /* Media */
  generateViaMedia = 'generateViaMedia',
  retryMedia = 'retryMedia',
  cancelMedia = 'cancelMedia',
  upscaleImage = 'upscaleImage',
  removeBackground = 'removeBackground',
  createVariations = 'createVariations',
  upsertMediaModel = 'upsertMediaModel',
  deleteMediaModel = 'deleteMediaModel',
  upsertMediaRoutingRule = 'upsertMediaRoutingRule',
  deleteMediaRoutingRule = 'deleteMediaRoutingRule',
  /* Provider Management */
  createProvider = 'createProvider',
  updateProvider = 'updateProvider',
  deleteProvider = 'deleteProvider',
  createProviderKey = 'createProviderKey',
  testProviderKey = 'testProviderKey',
  deleteProviderKey = 'deleteProviderKey',
  createProviderModel = 'createProviderModel',
  updateProviderModel = 'updateProviderModel',
  deleteProviderModel = 'deleteProviderModel',
  createRoutingRule = 'createRoutingRule',
  updateRoutingRule = 'updateRoutingRule',
  deleteRoutingRule = 'deleteRoutingRule',
  upsertSystemDefault = 'upsertSystemDefault',
}
